
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Screens;

import Objects.*;
import Controllers.*;
import Services.CellRenderer;
import Services.Controll_Images;
import Services.GerarPDF;
import Services.MyTableModel;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ButtonModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;

/**
 *
 * @author Gilberto 
 */
public class TelaAdocao extends javax.swing.JPanel {
    private MyTableModel modeloTabela;
    
    int posicaoImagem = -1;
    ControllerAnimal controllerAnimal = new ControllerAnimal();
    ImageIcon ImagemIconAnimal = new ImageIcon();
    ImageIcon ImagemIconAdotante = new ImageIcon();
    
    String ultimoPacote = "";
    //TelaMenu framePrincipal;
    
    public TelaAdocao() throws Exception {
        //framePrincipal = (TelaMenu) jf;
        initComponents();
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgFiltroPrenha = new javax.swing.ButtonGroup();
        bgFiltroVacinado = new javax.swing.ButtonGroup();
        bgFiltroCastrado = new javax.swing.ButtonGroup();
        bgFiltroSexo = new javax.swing.ButtonGroup();
        jpnBackground = new javax.swing.JPanel();
        jpnPaiLeft = new javax.swing.JPanel();
        jpnPrincipal = new javax.swing.JPanel();
        jpnDescricao = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        txt_imagem = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlDescricao = new javax.swing.JLabel();
        jlEspecie = new javax.swing.JLabel();
        jlNome = new javax.swing.JLabel();
        jlIdade = new javax.swing.JLabel();
        jlCor = new javax.swing.JLabel();
        jlSexo = new javax.swing.JLabel();
        jpnAtualizar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jpnAdotar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jpnExcluir = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jpnPesquisar = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jpnLista = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jCadastro = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        cxAdontanteNome = new javax.swing.JTextField();
        cxAdontanteEnderco = new javax.swing.JTextField();
        jpnFinalizar = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        cxAdontanteCpf = new javax.swing.JTextField();
        cxAdontanteTelefone = new javax.swing.JTextField();
        jpnFinalizar1 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();

        jpnBackground.setBackground(new java.awt.Color(255, 255, 255));
        jpnBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnPaiLeft.setBackground(new java.awt.Color(255, 255, 255));
        jpnPaiLeft.setLayout(new java.awt.CardLayout());

        jpnPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        jpnPrincipal.setPreferredSize(new java.awt.Dimension(300, 600));
        jpnPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnDescricao.setBackground(new java.awt.Color(255, 255, 255));
        jpnDescricao.setPreferredSize(new java.awt.Dimension(300, 1000));
        jpnDescricao.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(56, 0, 56));
        jLabel27.setText("Espécie");
        jpnDescricao.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, 20));

        jLabel28.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(56, 0, 56));
        jLabel28.setText("Nome");
        jpnDescricao.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 40, 20));

        jLabel29.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(56, 0, 56));
        jLabel29.setText("Idade");
        jpnDescricao.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 50, 20));

        jLabel32.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(56, 0, 56));
        jLabel32.setText("Cor");
        jpnDescricao.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, 20));

        jLabel36.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(56, 0, 56));
        jLabel36.setText("Sexo");
        jpnDescricao.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, 20));

        jLabel65.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(56, 0, 56));
        jLabel65.setText("Descrição");
        jpnDescricao.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 70, 30));

        txt_imagem.setBackground(new java.awt.Color(255, 255, 255));
        txt_imagem.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        txt_imagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_imagem.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(204, 204, 204)));
        jpnDescricao.add(txt_imagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 200, 150));
        jpnDescricao.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 1140, 20, 20));
        jpnDescricao.add(jlDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 160, 140));
        jpnDescricao.add(jlEspecie, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 160, 30));
        jpnDescricao.add(jlNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 160, 30));
        jpnDescricao.add(jlIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 160, 30));
        jpnDescricao.add(jlCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 160, 30));
        jpnDescricao.add(jlSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 160, 30));

        jpnPrincipal.add(jpnDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jpnAtualizar.setBackground(new java.awt.Color(56, 0, 56));
        jpnAtualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnAtualizarMouseClicked(evt);
            }
        });
        jpnAtualizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Atualizar");
        jpnAtualizar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        jpnPrincipal.add(jpnAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 80, 30));

        jpnAdotar.setBackground(new java.awt.Color(56, 0, 56));
        jpnAdotar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnAdotarMouseClicked(evt);
            }
        });
        jpnAdotar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Adotar");
        jpnAdotar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        jpnPrincipal.add(jpnAdotar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 530, 80, 30));

        jpnExcluir.setBackground(new java.awt.Color(56, 0, 56));
        jpnExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnExcluirMouseClicked(evt);
            }
        });
        jpnExcluir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Excluir");
        jpnExcluir.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        jpnPrincipal.add(jpnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, 80, 30));

        jpnPesquisar.setBackground(new java.awt.Color(56, 0, 56));
        jpnPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnPesquisarMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Filtrar");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jpnPesquisarLayout = new javax.swing.GroupLayout(jpnPesquisar);
        jpnPesquisar.setLayout(jpnPesquisarLayout);
        jpnPesquisarLayout.setHorizontalGroup(
            jpnPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        jpnPesquisarLayout.setVerticalGroup(
            jpnPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jpnPrincipal.add(jpnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 80, 30));

        jpnLista.setBackground(new java.awt.Color(56, 0, 56));
        jpnLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnListaMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Gerar lista");

        javax.swing.GroupLayout jpnListaLayout = new javax.swing.GroupLayout(jpnLista);
        jpnLista.setLayout(jpnListaLayout);
        jpnListaLayout.setHorizontalGroup(
            jpnListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnListaLayout.setVerticalGroup(
            jpnListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jpnPrincipal.add(jpnLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 80, 30));

        jpnPaiLeft.add(jpnPrincipal, "jpnPrincipal");

        jpnBackground.add(jpnPaiLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 580));

        jCadastro.setBackground(new java.awt.Color(255, 255, 255));
        jCadastro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Open Sans SemiBold", 0, 22)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(56, 0, 56));
        jLabel23.setText("Cadastro de Adotante");
        jCadastro.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 230, 40));

        cxAdontanteNome.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        cxAdontanteNome.setForeground(new java.awt.Color(56, 0, 56));
        cxAdontanteNome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(131, 106, 131), 1, true));
        cxAdontanteNome.setPreferredSize(new java.awt.Dimension(300, 40));
        cxAdontanteNome.setSelectionColor(new java.awt.Color(149, 113, 149));
        jCadastro.add(cxAdontanteNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, 30));

        cxAdontanteEnderco.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        cxAdontanteEnderco.setForeground(new java.awt.Color(56, 0, 56));
        cxAdontanteEnderco.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(131, 106, 131), 1, true));
        cxAdontanteEnderco.setPreferredSize(new java.awt.Dimension(300, 40));
        cxAdontanteEnderco.setSelectionColor(new java.awt.Color(149, 113, 149));
        jCadastro.add(cxAdontanteEnderco, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, -1, 70));

        jpnFinalizar.setBackground(new java.awt.Color(56, 0, 56));
        jpnFinalizar.setPreferredSize(new java.awt.Dimension(80, 40));
        jpnFinalizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpnFinalizarMousePressed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Cancelar");
        jLabel25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel25.setPreferredSize(new java.awt.Dimension(58, 16));
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel25MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jpnFinalizarLayout = new javax.swing.GroupLayout(jpnFinalizar);
        jpnFinalizar.setLayout(jpnFinalizarLayout);
        jpnFinalizarLayout.setHorizontalGroup(
            jpnFinalizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnFinalizarLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpnFinalizarLayout.setVerticalGroup(
            jpnFinalizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnFinalizarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        jCadastro.add(jpnFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 110, -1));

        jLabel24.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(56, 0, 56));
        jLabel24.setText("Nome");
        jCadastro.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, 30));

        jLabel26.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(56, 0, 56));
        jLabel26.setText("CPF");
        jCadastro.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, 30));

        jLabel30.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(56, 0, 56));
        jLabel30.setText("Telefone");
        jCadastro.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, 30));

        jLabel31.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(56, 0, 56));
        jLabel31.setText("Endereço");
        jCadastro.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, 30));

        cxAdontanteCpf.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        cxAdontanteCpf.setForeground(new java.awt.Color(56, 0, 56));
        cxAdontanteCpf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(131, 106, 131), 1, true));
        cxAdontanteCpf.setPreferredSize(new java.awt.Dimension(300, 40));
        cxAdontanteCpf.setSelectionColor(new java.awt.Color(149, 113, 149));
        jCadastro.add(cxAdontanteCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, 30));

        cxAdontanteTelefone.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        cxAdontanteTelefone.setForeground(new java.awt.Color(56, 0, 56));
        cxAdontanteTelefone.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(131, 106, 131), 1, true));
        cxAdontanteTelefone.setPreferredSize(new java.awt.Dimension(300, 40));
        cxAdontanteTelefone.setSelectionColor(new java.awt.Color(149, 113, 149));
        jCadastro.add(cxAdontanteTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, 30));

        jpnFinalizar1.setBackground(new java.awt.Color(56, 0, 56));
        jpnFinalizar1.setPreferredSize(new java.awt.Dimension(80, 40));
        jpnFinalizar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpnFinalizar1MousePressed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Finalizar");
        jLabel33.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel33.setPreferredSize(new java.awt.Dimension(58, 16));
        jLabel33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel33MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jpnFinalizar1Layout = new javax.swing.GroupLayout(jpnFinalizar1);
        jpnFinalizar1.setLayout(jpnFinalizar1Layout);
        jpnFinalizar1Layout.setHorizontalGroup(
            jpnFinalizar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnFinalizar1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpnFinalizar1Layout.setVerticalGroup(
            jpnFinalizar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnFinalizar1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        jCadastro.add(jpnFinalizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, 110, -1));

        jpnBackground.add(jCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, -10, 700, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jpnFinalizarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnFinalizarMousePressed

    }//GEN-LAST:event_jpnFinalizarMousePressed

    private void jLabel25MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MousePressed

    }//GEN-LAST:event_jLabel25MousePressed

    private void jpnListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnListaMouseClicked
        GerarPDF gerarPDF = new GerarPDF();
        try {
            gerarPDF.gerar(modeloTabela.getListAnimal());
        } catch (Exception ex) {
            Logger.getLogger(TelaAdocao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jpnListaMouseClicked

    private void jpnPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnPesquisarMouseClicked

    }//GEN-LAST:event_jpnPesquisarMouseClicked

    private void jpnExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnExcluirMouseClicked

    }//GEN-LAST:event_jpnExcluirMouseClicked

    private void jpnAdotarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnAdotarMouseClicked

    }//GEN-LAST:event_jpnAdotarMouseClicked

    private void jpnAtualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnAtualizarMouseClicked

    }//GEN-LAST:event_jpnAtualizarMouseClicked

    private void jLabel33MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel33MousePressed

    private void jpnFinalizar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnFinalizar1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpnFinalizar1MousePressed
    
    private void preencherComboBoxAnimaisAdocao(JComboBox jcbAnimaisParaAdotar){
        ControllerAnimal daoAnimal = new ControllerAnimal();
        try {
            for(Animal animal : daoAnimal.getList(false)){
                jcbAnimaisParaAdotar.addItem(animal);
            }
        } catch (Exception ex) {
              JOptionPane.showMessageDialog(null, ex.getMessage(),
                    "Ocorreu um erro durante a execução do programa", JOptionPane.INFORMATION_MESSAGE);
            Logger.getLogger(TelaAdocao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
        
    public void adicionarImagem(JLabel fotinha) throws IOException {
        JFileChooser jFileChooser1 = new javax.swing.JFileChooser(ultimoPacote);
        jFileChooser1.showOpenDialog(null);
        File arquivo = jFileChooser1.getSelectedFile();
        
        if (arquivo != null) {
            ultimoPacote = arquivo.getPath();
            BufferedImage bufferedImage = ImageIO.read(new File(ultimoPacote));
            Image image = bufferedImage.getScaledInstance(500,
                    500, Image.SCALE_SMOOTH);
           
            ImageIcon imagem = new ImageIcon(image);
            Controll_Images redimencionar = new Controll_Images();
            imagem = redimencionar.redimensionar_imagem(imagem);
            fotinha.setIcon(imagem);
            ImagemIconAnimal = imagem;
        } else {
            System.out.println("Deu muito ruim");
        }
    }
    
            
    
            

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgFiltroCastrado;
    private javax.swing.ButtonGroup bgFiltroPrenha;
    private javax.swing.ButtonGroup bgFiltroSexo;
    private javax.swing.ButtonGroup bgFiltroVacinado;
    private javax.swing.JTextField cxAdontanteCpf;
    private javax.swing.JTextField cxAdontanteEnderco;
    private javax.swing.JTextField cxAdontanteNome;
    private javax.swing.JTextField cxAdontanteTelefone;
    private javax.swing.JPanel jCadastro;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jlCor;
    private javax.swing.JLabel jlDescricao;
    private javax.swing.JLabel jlEspecie;
    private javax.swing.JLabel jlIdade;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlSexo;
    private javax.swing.JPanel jpnAdotar;
    private javax.swing.JPanel jpnAtualizar;
    private javax.swing.JPanel jpnBackground;
    private javax.swing.JPanel jpnDescricao;
    private javax.swing.JPanel jpnExcluir;
    private javax.swing.JPanel jpnFinalizar;
    private javax.swing.JPanel jpnFinalizar1;
    private javax.swing.JPanel jpnLista;
    private javax.swing.JPanel jpnPaiLeft;
    private javax.swing.JPanel jpnPesquisar;
    private javax.swing.JPanel jpnPrincipal;
    private javax.swing.JLabel txt_imagem;
    // End of variables declaration//GEN-END:variables

}
