/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Screens;

import Objects.Animal;
import Controllers.ControllerAnimal;
import Services.Controll_Images;
import java.awt.Color;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.sql.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Gilberto
 */
public class TelaDeCadastroDeAnimais extends javax.swing.JPanel {

    /**
     * Creates new form panelCadastro
     */
    ImageIcon ImagemIconAnimal = new ImageIcon();
    String ultimoPacote = "";
    public Animal animal;

    public TelaDeCadastroDeAnimais() {
        for(UIManager.LookAndFeelInfo info: UIManager.getInstalledLookAndFeels()){
            if("Windows".equals(info.getName())){
                try {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(TelaDeCadastroDeAnimais.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(TelaDeCadastroDeAnimais.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(TelaDeCadastroDeAnimais.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(TelaDeCadastroDeAnimais.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        initComponents();
        
        startArrayList();
        jpQual.setVisible(false);
        pnDoencas.setVisible(false);
        for (int i = 0; i < listComboBox.size(); i++) {
            backgroundComboBox(listComboBox.get(i));
        }

    }
    ControllerAnimal cAnimal = new ControllerAnimal();
    ArrayList<JComboBox> listComboBox = new ArrayList<>();

    public void startArrayList() {
        listComboBox.add(jComboEspecie);
        listComboBox.add(jComboPorte);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jComboEspecie1 = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jComboBairro1 = new javax.swing.JComboBox<>();
        jLabel38 = new javax.swing.JLabel();
        jtx_raca1 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        btn_cadastrar1 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        panelTamanho1 = new javax.swing.JPanel();
        jComboPorte1 = new javax.swing.JComboBox<>();
        jLabel53 = new javax.swing.JLabel();
        jComboTemperamento1 = new javax.swing.JComboBox<>();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jtx_cor1 = new javax.swing.JTextField();
        jtx_nome1 = new javax.swing.JTextField();
        jpQual1 = new javax.swing.JPanel();
        jtxoutraraca1 = new javax.swing.JTextField();
        qual2 = new javax.swing.JLabel();
        somente1 = new javax.swing.JLabel();
        jtx_nomeContato1 = new javax.swing.JTextField();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jtx_idade1 = new javax.swing.JFormattedTextField();
        jrMacho1 = new javax.swing.JRadioButton();
        rjFemea1 = new javax.swing.JRadioButton();
        jrVacinadoNao1 = new javax.swing.JRadioButton();
        jrVacinadoSim1 = new javax.swing.JRadioButton();
        jrCastradoSim1 = new javax.swing.JRadioButton();
        jrCastradoNao1 = new javax.swing.JRadioButton();
        jrDoenteSim1 = new javax.swing.JRadioButton();
        jrDoenteNao1 = new javax.swing.JRadioButton();
        jrAcidentadoSim1 = new javax.swing.JRadioButton();
        jrAcidentadoNao1 = new javax.swing.JRadioButton();
        pnPrenha1 = new javax.swing.JPanel();
        jblPrenha1 = new javax.swing.JLabel();
        jrPrenhaSim1 = new javax.swing.JRadioButton();
        jrPrenhaNao1 = new javax.swing.JRadioButton();
        pnDoencas1 = new javax.swing.JPanel();
        jlbdoenca1 = new javax.swing.JLabel();
        jtxdoenca1 = new javax.swing.JTextField();
        pnAcidentado1 = new javax.swing.JPanel();
        jlbdoenca3 = new javax.swing.JLabel();
        jtxacidente1 = new javax.swing.JTextField();
        jtx_telefoneContato1 = new javax.swing.JFormattedTextField();
        jLabel75 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        qual3 = new javax.swing.JLabel();
        jrComunitarioSim1 = new javax.swing.JRadioButton();
        jrComunitarioNao1 = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtx_descricao1 = new javax.swing.JTextArea();
        txt_imagem1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jpnAddFoto1 = new javax.swing.JPanel();
        LABELCOMERRO = new javax.swing.JLabel();
        jpnExcluirFoto1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jComboEspecie = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jtx_raca = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        btn_cadastrar = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        panelTamanho = new javax.swing.JPanel();
        jComboPorte = new javax.swing.JComboBox<>();
        jLabel50 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jtx_cor = new javax.swing.JTextField();
        jtx_nome = new javax.swing.JTextField();
        jpQual = new javax.swing.JPanel();
        jtxoutraraca = new javax.swing.JTextField();
        qual = new javax.swing.JLabel();
        idadeAnimal = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jrMacho = new javax.swing.JRadioButton();
        rjFemea = new javax.swing.JRadioButton();
        jrVacinadoNao = new javax.swing.JRadioButton();
        jrVacinadoSim = new javax.swing.JRadioButton();
        jrCastradoSim = new javax.swing.JRadioButton();
        jrCastradoNao = new javax.swing.JRadioButton();
        jrDoenteSim = new javax.swing.JRadioButton();
        jrDoenteNao = new javax.swing.JRadioButton();
        pnDoencas = new javax.swing.JPanel();
        jlbdoenca = new javax.swing.JLabel();
        jtxdoenca = new javax.swing.JTextField();
        jLabel74 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtx_descricao = new javax.swing.JTextArea();
        txt_imagem = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jpnAddFoto = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jpnExcluirFoto = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(56, 0, 56));
        jLabel33.setText("Espécie");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, 30));

        jComboEspecie1.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jComboEspecie1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cachorro", "Gato", "Outro" }));
        jComboEspecie1.setKeySelectionManager(null);
        jComboEspecie1.setPreferredSize(new java.awt.Dimension(56, 30));
        jComboEspecie1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboEspecie1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboEspecie1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 150, -1));

        jLabel34.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(56, 0, 56));
        jLabel34.setText("Nome");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 50, 30));

        jLabel35.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(56, 0, 56));
        jLabel35.setText("Idade");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 50, 30));

        jLabel37.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(56, 0, 56));
        jLabel37.setText("Porte");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, 30));

        jComboBairro1.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jComboBairro1.setForeground(new java.awt.Color(56, 0, 56));
        jComboBairro1.setMaximumRowCount(100);
        jComboBairro1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1° de Maio", "Alto Chalé", "Alto São Francisco", "Amália Rodrigues", "Bandeirantes", "Belvedere", "Campus Alto Paraopeba", "Carreiras", "Castiliano", "Centro", "Estiva", "Inconfidentes", "Itatiaia", "João Gote", "Luzia Augusta", "Nova Serrana", "Novo Horizonte", "Olaria", "Pioneiros", "Pires", "Siderurgia", "Soledade", "Tiradentes", "Zona Rural" }));
        jPanel1.add(jComboBairro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 520, 185, 30));

        jLabel38.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(56, 0, 56));
        jLabel38.setText("Raça");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, 30));

        jtx_raca1.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jtx_raca1.setForeground(new java.awt.Color(56, 0, 56));
        jtx_raca1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(131, 106, 131), 1, true));
        jtx_raca1.setSelectionColor(new java.awt.Color(149, 113, 149));
        jPanel1.add(jtx_raca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 300, 30));

        jLabel39.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(56, 0, 56));
        jLabel39.setText("Cor");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, 30));

        jLabel43.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(56, 0, 56));
        jLabel43.setText("Fotos");
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1040, -1, 30));

        btn_cadastrar1.setBackground(new java.awt.Color(56, 0, 56));
        btn_cadastrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cadastrar1MouseClicked(evt);
            }
        });
        btn_cadastrar1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel49.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("Finalizar");
        btn_cadastrar1.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 8, 63, 16));

        jPanel1.add(btn_cadastrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 1290, 150, 30));

        panelTamanho1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelTamanho1Layout = new javax.swing.GroupLayout(panelTamanho1);
        panelTamanho1.setLayout(panelTamanho1Layout);
        panelTamanho1Layout.setHorizontalGroup(
            panelTamanho1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        panelTamanho1Layout.setVerticalGroup(
            panelTamanho1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(panelTamanho1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 1320, 90, 40));

        jComboPorte1.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jComboPorte1.setForeground(new java.awt.Color(56, 0, 56));
        jComboPorte1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mini", "Pequeno", "Médio", "Grande", "Gigante" }));
        jComboPorte1.setKeySelectionManager(null);
        jPanel1.add(jComboPorte1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 150, 30));

        jLabel53.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(56, 0, 56));
        jLabel53.setText("Temperamento");
        jPanel1.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 110, 30));

        jComboTemperamento1.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jComboTemperamento1.setForeground(new java.awt.Color(56, 0, 56));
        jComboTemperamento1.setMaximumRowCount(10);
        jComboTemperamento1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Medroso", "Agressivo", "Calmo", "Nervoso", "Estressável", "Tímido", "Ousado", "Corajoso", "Curioso" }));
        jPanel1.add(jComboTemperamento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 150, 30));

        jLabel54.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(56, 0, 56));
        jLabel54.setText("Bairro Encontrado");
        jPanel1.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 130, 30));

        jLabel55.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(56, 0, 56));
        jLabel55.setText("Vacinado");
        jPanel1.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 70, 30));

        jLabel40.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(56, 0, 56));
        jLabel40.setText("Sexo");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, 30));

        jLabel56.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(56, 0, 56));
        jLabel56.setText("Doente");
        jPanel1.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 700, 60, 30));

        jLabel57.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(56, 0, 56));
        jLabel57.setText("Castrado");
        jPanel1.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 640, 70, 30));

        jtx_cor1.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jtx_cor1.setForeground(new java.awt.Color(56, 0, 56));
        jtx_cor1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(131, 106, 131), 1, true));
        jtx_cor1.setSelectionColor(new java.awt.Color(149, 113, 149));
        jPanel1.add(jtx_cor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 300, 30));

        jtx_nome1.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jtx_nome1.setForeground(new java.awt.Color(56, 0, 56));
        jtx_nome1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(131, 106, 131), 1, true));
        jtx_nome1.setOpaque(false);
        jtx_nome1.setPreferredSize(new java.awt.Dimension(300, 30));
        jtx_nome1.setSelectionColor(new java.awt.Color(149, 113, 149));
        jPanel1.add(jtx_nome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        jpQual1.setBackground(new java.awt.Color(255, 255, 255));

        jtxoutraraca1.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jtxoutraraca1.setForeground(new java.awt.Color(56, 0, 56));
        jtxoutraraca1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(131, 106, 131), 1, true));
        jtxoutraraca1.setSelectionColor(new java.awt.Color(149, 113, 149));

        qual2.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        qual2.setForeground(new java.awt.Color(56, 0, 56));
        qual2.setText("Qual");

        javax.swing.GroupLayout jpQual1Layout = new javax.swing.GroupLayout(jpQual1);
        jpQual1.setLayout(jpQual1Layout);
        jpQual1Layout.setHorizontalGroup(
            jpQual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
            .addGroup(jpQual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpQual1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(qual2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(jtxoutraraca1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jpQual1Layout.setVerticalGroup(
            jpQual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(jpQual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpQual1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jpQual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(qual2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtxoutraraca1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(jpQual1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 240, 30));

        somente1.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        somente1.setForeground(new java.awt.Color(56, 0, 56));
        somente1.setText("*Somente números");
        jPanel1.add(somente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 160, 30));

        jtx_nomeContato1.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jtx_nomeContato1.setForeground(new java.awt.Color(56, 0, 56));
        jtx_nomeContato1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(131, 106, 131), 1, true));
        jtx_nomeContato1.setSelectionColor(new java.awt.Color(149, 113, 149));
        jtx_nomeContato1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtx_nomeContato1ActionPerformed(evt);
            }
        });
        jPanel1.add(jtx_nomeContato1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 820, 300, 30));

        jLabel68.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(56, 0, 56));
        jLabel68.setText("Nome do Contato");
        jPanel1.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 820, 120, 30));

        jLabel69.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(56, 0, 56));
        jLabel69.setText("Descrição");
        jPanel1.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 940, 70, 30));

        jLabel70.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(56, 0, 56));
        jLabel70.setText("Acidentado");
        jPanel1.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 760, 80, 30));

        jLabel71.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(56, 0, 56));
        jLabel71.setText("Telefone para Contato");
        jPanel1.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 880, 150, 30));

        jtx_idade1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(131, 106, 131), 1, true));
        jtx_idade1.setForeground(new java.awt.Color(56, 0, 56));
        try {
            jtx_idade1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtx_idade1.setSelectionColor(new java.awt.Color(149, 113, 149));
        jPanel1.add(jtx_idade1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 300, 30));

        jrMacho1.setBackground(new java.awt.Color(255, 255, 255));
        jrMacho1.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jrMacho1.setForeground(new java.awt.Color(56, 0, 56));
        jrMacho1.setText("Macho");
        jrMacho1.setOpaque(false);
        jrMacho1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrMacho1ActionPerformed(evt);
            }
        });
        jPanel1.add(jrMacho1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, -1, 30));

        rjFemea1.setBackground(new java.awt.Color(255, 255, 255));
        rjFemea1.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        rjFemea1.setForeground(new java.awt.Color(56, 0, 56));
        rjFemea1.setText("Fêmea");
        rjFemea1.setOpaque(false);
        rjFemea1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rjFemea1ActionPerformed(evt);
            }
        });
        jPanel1.add(rjFemea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, -1, 30));

        jrVacinadoNao1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(jrVacinadoNao1);
        jrVacinadoNao1.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jrVacinadoNao1.setForeground(new java.awt.Color(56, 0, 56));
        jrVacinadoNao1.setText("Não");
        jrVacinadoNao1.setOpaque(false);
        jPanel1.add(jrVacinadoNao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 580, -1, 30));

        jrVacinadoSim1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(jrVacinadoSim1);
        jrVacinadoSim1.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jrVacinadoSim1.setForeground(new java.awt.Color(56, 0, 56));
        jrVacinadoSim1.setText("Sim");
        jrVacinadoSim1.setOpaque(false);
        jPanel1.add(jrVacinadoSim1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 580, -1, 30));

        jrCastradoSim1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup4.add(jrCastradoSim1);
        jrCastradoSim1.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jrCastradoSim1.setForeground(new java.awt.Color(56, 0, 56));
        jrCastradoSim1.setText("Sim");
        jrCastradoSim1.setOpaque(false);
        jPanel1.add(jrCastradoSim1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 640, -1, 30));

        jrCastradoNao1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup4.add(jrCastradoNao1);
        jrCastradoNao1.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jrCastradoNao1.setForeground(new java.awt.Color(56, 0, 56));
        jrCastradoNao1.setText("Não");
        jrCastradoNao1.setOpaque(false);
        jPanel1.add(jrCastradoNao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 640, -1, 30));

        jrDoenteSim1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jrDoenteSim1);
        jrDoenteSim1.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jrDoenteSim1.setForeground(new java.awt.Color(56, 0, 56));
        jrDoenteSim1.setText("Sim");
        jrDoenteSim1.setOpaque(false);
        jrDoenteSim1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrDoenteSim1ActionPerformed(evt);
            }
        });
        jPanel1.add(jrDoenteSim1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 700, -1, 30));

        jrDoenteNao1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jrDoenteNao1);
        jrDoenteNao1.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jrDoenteNao1.setForeground(new java.awt.Color(56, 0, 56));
        jrDoenteNao1.setText("Não");
        jrDoenteNao1.setOpaque(false);
        jrDoenteNao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrDoenteNao1ActionPerformed(evt);
            }
        });
        jPanel1.add(jrDoenteNao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 700, -1, 30));

        jrAcidentadoSim1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(jrAcidentadoSim1);
        jrAcidentadoSim1.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jrAcidentadoSim1.setForeground(new java.awt.Color(56, 0, 56));
        jrAcidentadoSim1.setText("Sim");
        jrAcidentadoSim1.setOpaque(false);
        jrAcidentadoSim1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrAcidentadoSim1ActionPerformed(evt);
            }
        });
        jPanel1.add(jrAcidentadoSim1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 760, -1, 30));

        jrAcidentadoNao1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(jrAcidentadoNao1);
        jrAcidentadoNao1.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jrAcidentadoNao1.setForeground(new java.awt.Color(56, 0, 56));
        jrAcidentadoNao1.setText("Não");
        jrAcidentadoNao1.setOpaque(false);
        jrAcidentadoNao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrAcidentadoNao1ActionPerformed(evt);
            }
        });
        jPanel1.add(jrAcidentadoNao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 760, -1, 30));

        pnPrenha1.setBackground(new java.awt.Color(255, 255, 255));
        pnPrenha1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblPrenha1.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jblPrenha1.setForeground(new java.awt.Color(56, 0, 56));
        jblPrenha1.setText("Prenha");
        pnPrenha1.add(jblPrenha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 30));

        jrPrenhaSim1.setBackground(new java.awt.Color(255, 255, 255));
        jrPrenhaSim1.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jrPrenhaSim1.setForeground(new java.awt.Color(56, 0, 56));
        jrPrenhaSim1.setText("Sim");
        jrPrenhaSim1.setOpaque(false);
        pnPrenha1.add(jrPrenhaSim1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 30));

        jrPrenhaNao1.setBackground(new java.awt.Color(255, 255, 255));
        jrPrenhaNao1.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jrPrenhaNao1.setForeground(new java.awt.Color(56, 0, 56));
        jrPrenhaNao1.setText("Não");
        jrPrenhaNao1.setOpaque(false);
        pnPrenha1.add(jrPrenhaNao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, -1, 30));

        jPanel1.add(pnPrenha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 190, -1));

        pnDoencas1.setBackground(new java.awt.Color(255, 255, 255));
        pnDoencas1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbdoenca1.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jlbdoenca1.setForeground(new java.awt.Color(56, 0, 56));
        jlbdoenca1.setText("Quais doenças");
        pnDoencas1.add(jlbdoenca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jtxdoenca1.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jtxdoenca1.setForeground(new java.awt.Color(56, 0, 56));
        jtxdoenca1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(131, 106, 131), 1, true));
        jtxdoenca1.setSelectionColor(new java.awt.Color(149, 113, 149));
        pnDoencas1.add(jtxdoenca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 190, 30));

        jPanel1.add(pnDoencas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 700, -1, 30));

        pnAcidentado1.setBackground(new java.awt.Color(255, 255, 255));
        pnAcidentado1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbdoenca3.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jlbdoenca3.setForeground(new java.awt.Color(56, 0, 56));
        jlbdoenca3.setText("Qual acidente");
        pnAcidentado1.add(jlbdoenca3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jtxacidente1.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jtxacidente1.setForeground(new java.awt.Color(56, 0, 56));
        jtxacidente1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(131, 106, 131), 1, true));
        jtxacidente1.setSelectionColor(new java.awt.Color(149, 113, 149));
        pnAcidentado1.add(jtxacidente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 190, 30));

        jPanel1.add(pnAcidentado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 760, 310, 30));

        jtx_telefoneContato1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(131, 106, 131), 1, true));
        jtx_telefoneContato1.setForeground(new java.awt.Color(56, 0, 56));
        try {
            jtx_telefoneContato1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtx_telefoneContato1.setSelectionColor(new java.awt.Color(149, 113, 149));
        jPanel1.add(jtx_telefoneContato1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 880, 300, 30));
        jPanel1.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, 60, -1));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        qual3.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        qual3.setForeground(new java.awt.Color(56, 0, 56));
        qual3.setText("Comunitário");

        jrComunitarioSim1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup5.add(jrComunitarioSim1);
        jrComunitarioSim1.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jrComunitarioSim1.setForeground(new java.awt.Color(56, 0, 56));
        jrComunitarioSim1.setText("Sim");
        jrComunitarioSim1.setOpaque(false);
        jrComunitarioSim1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrComunitarioSim1ActionPerformed(evt);
            }
        });

        jrComunitarioNao1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup5.add(jrComunitarioNao1);
        jrComunitarioNao1.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jrComunitarioNao1.setForeground(new java.awt.Color(56, 0, 56));
        jrComunitarioNao1.setText("Não");
        jrComunitarioNao1.setOpaque(false);
        jrComunitarioNao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrComunitarioNao1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(qual3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jrComunitarioSim1)
                .addGap(21, 21, 21)
                .addComponent(jrComunitarioNao1))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(qual3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrComunitarioSim1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrComunitarioNao1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 220, 30));

        jtx_descricao1.setColumns(20);
        jtx_descricao1.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jtx_descricao1.setForeground(new java.awt.Color(56, 0, 56));
        jtx_descricao1.setLineWrap(true);
        jtx_descricao1.setRows(5);
        jtx_descricao1.setTabSize(0);
        jtx_descricao1.setWrapStyleWord(true);
        jtx_descricao1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jtx_descricao1.setHighlighter(null);
        jtx_descricao1.setSelectionColor(new java.awt.Color(149, 113, 149));
        jScrollPane2.setViewportView(jtx_descricao1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 940, 490, -1));

        txt_imagem1.setBackground(new java.awt.Color(255, 255, 255));
        txt_imagem1.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        txt_imagem1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_imagem1.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(204, 204, 204)));
        jPanel1.add(txt_imagem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 1090, 200, 150));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 1280, 20, 20));

        jpnAddFoto1.setBackground(new java.awt.Color(56, 0, 56));
        jpnAddFoto1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnAddFoto1MouseClicked(evt);
            }
        });
        jpnAddFoto1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LABELCOMERRO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LABELCOMERRO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-mais-20 (1).png"))); // NOI18N
        jpnAddFoto1.add(LABELCOMERRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        jPanel1.add(jpnAddFoto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 1250, 30, 30));

        jpnExcluirFoto1.setBackground(new java.awt.Color(56, 0, 56));
        jpnExcluirFoto1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnExcluirFoto1MouseClicked(evt);
            }
        });
        jpnExcluirFoto1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-cancelar-20 (1).png"))); // NOI18N
        jpnExcluirFoto1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        jPanel1.add(jpnExcluirFoto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 1250, 30, 30));

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(700, 1100));
        setPreferredSize(new java.awt.Dimension(700, 1100));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(56, 0, 56));
        jLabel27.setText("Espécie");
        add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, 30));

        jComboEspecie.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jComboEspecie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cachorro", "Gato", "Outro" }));
        jComboEspecie.setKeySelectionManager(null);
        jComboEspecie.setPreferredSize(new java.awt.Dimension(56, 30));
        jComboEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboEspecieActionPerformed(evt);
            }
        });
        add(jComboEspecie, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 150, -1));

        jLabel28.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(56, 0, 56));
        jLabel28.setText("Nome");
        add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 50, 30));

        jLabel29.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(56, 0, 56));
        jLabel29.setText("Idade");
        add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 50, 30));

        jLabel30.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(56, 0, 56));
        jLabel30.setText("Porte");
        add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, 30));

        jLabel31.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(56, 0, 56));
        jLabel31.setText("Raça");
        add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, 30));

        jtx_raca.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jtx_raca.setForeground(new java.awt.Color(56, 0, 56));
        jtx_raca.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(131, 106, 131), 1, true));
        jtx_raca.setSelectionColor(new java.awt.Color(149, 113, 149));
        add(jtx_raca, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 300, 30));

        jLabel32.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(56, 0, 56));
        jLabel32.setText("Cor");
        add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, 30));

        jLabel42.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(56, 0, 56));
        jLabel42.setText("Fotos");
        add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 760, -1, 30));

        btn_cadastrar.setBackground(new java.awt.Color(56, 0, 56));
        btn_cadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cadastrarMouseClicked(evt);
            }
        });
        btn_cadastrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel46.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Finalizar");
        btn_cadastrar.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 8, 63, 16));

        add(btn_cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 1010, 150, 30));

        panelTamanho.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelTamanhoLayout = new javax.swing.GroupLayout(panelTamanho);
        panelTamanho.setLayout(panelTamanhoLayout);
        panelTamanhoLayout.setHorizontalGroup(
            panelTamanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        panelTamanhoLayout.setVerticalGroup(
            panelTamanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        add(panelTamanho, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 1320, 90, 40));

        jComboPorte.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jComboPorte.setForeground(new java.awt.Color(56, 0, 56));
        jComboPorte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mini", "Pequeno", "Médio", "Grande", "Gigante" }));
        jComboPorte.setKeySelectionManager(null);
        add(jComboPorte, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 150, 30));

        jLabel50.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(56, 0, 56));
        jLabel50.setText("Vacinado");
        add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 70, 30));

        jLabel36.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(56, 0, 56));
        jLabel36.setText("Sexo");
        add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, 30));

        jLabel51.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(56, 0, 56));
        jLabel51.setText("Doente");
        add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 60, 30));

        jLabel52.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(56, 0, 56));
        jLabel52.setText("Castrado");
        add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 70, 30));

        jtx_cor.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jtx_cor.setForeground(new java.awt.Color(56, 0, 56));
        jtx_cor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(131, 106, 131), 1, true));
        jtx_cor.setSelectionColor(new java.awt.Color(149, 113, 149));
        add(jtx_cor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 300, 30));

        jtx_nome.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jtx_nome.setForeground(new java.awt.Color(56, 0, 56));
        jtx_nome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(131, 106, 131), 1, true));
        jtx_nome.setOpaque(false);
        jtx_nome.setPreferredSize(new java.awt.Dimension(300, 30));
        jtx_nome.setSelectionColor(new java.awt.Color(149, 113, 149));
        add(jtx_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        jpQual.setBackground(new java.awt.Color(255, 255, 255));

        jtxoutraraca.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jtxoutraraca.setForeground(new java.awt.Color(56, 0, 56));
        jtxoutraraca.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(131, 106, 131), 1, true));
        jtxoutraraca.setSelectionColor(new java.awt.Color(149, 113, 149));

        qual.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        qual.setForeground(new java.awt.Color(56, 0, 56));
        qual.setText("Qual");

        javax.swing.GroupLayout jpQualLayout = new javax.swing.GroupLayout(jpQual);
        jpQual.setLayout(jpQualLayout);
        jpQualLayout.setHorizontalGroup(
            jpQualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
            .addGroup(jpQualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpQualLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(qual, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(jtxoutraraca, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jpQualLayout.setVerticalGroup(
            jpQualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(jpQualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpQualLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jpQualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(qual, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtxoutraraca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        add(jpQual, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 240, 30));

        idadeAnimal.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        idadeAnimal.setForeground(new java.awt.Color(56, 0, 56));
        add(idadeAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 160, 30));

        jLabel65.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(56, 0, 56));
        jLabel65.setText("Descrição");
        add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 630, 70, 30));

        jrMacho.setBackground(new java.awt.Color(255, 255, 255));
        jrMacho.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jrMacho.setForeground(new java.awt.Color(56, 0, 56));
        jrMacho.setText("Macho");
        jrMacho.setOpaque(false);
        jrMacho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrMachoActionPerformed(evt);
            }
        });
        add(jrMacho, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, -1, 30));

        rjFemea.setBackground(new java.awt.Color(255, 255, 255));
        rjFemea.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        rjFemea.setForeground(new java.awt.Color(56, 0, 56));
        rjFemea.setText("Fêmea");
        rjFemea.setOpaque(false);
        rjFemea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rjFemeaActionPerformed(evt);
            }
        });
        add(rjFemea, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, -1, 30));

        jrVacinadoNao.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(jrVacinadoNao);
        jrVacinadoNao.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jrVacinadoNao.setForeground(new java.awt.Color(56, 0, 56));
        jrVacinadoNao.setText("Não");
        jrVacinadoNao.setOpaque(false);
        add(jrVacinadoNao, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, -1, 30));

        jrVacinadoSim.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(jrVacinadoSim);
        jrVacinadoSim.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jrVacinadoSim.setForeground(new java.awt.Color(56, 0, 56));
        jrVacinadoSim.setText("Sim");
        jrVacinadoSim.setOpaque(false);
        add(jrVacinadoSim, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, -1, 30));

        jrCastradoSim.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup4.add(jrCastradoSim);
        jrCastradoSim.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jrCastradoSim.setForeground(new java.awt.Color(56, 0, 56));
        jrCastradoSim.setText("Sim");
        jrCastradoSim.setOpaque(false);
        add(jrCastradoSim, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, -1, 30));

        jrCastradoNao.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup4.add(jrCastradoNao);
        jrCastradoNao.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jrCastradoNao.setForeground(new java.awt.Color(56, 0, 56));
        jrCastradoNao.setText("Não");
        jrCastradoNao.setOpaque(false);
        add(jrCastradoNao, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, -1, 30));

        jrDoenteSim.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jrDoenteSim);
        jrDoenteSim.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jrDoenteSim.setForeground(new java.awt.Color(56, 0, 56));
        jrDoenteSim.setText("Sim");
        jrDoenteSim.setOpaque(false);
        jrDoenteSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrDoenteSimActionPerformed(evt);
            }
        });
        add(jrDoenteSim, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 550, -1, 30));

        jrDoenteNao.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jrDoenteNao);
        jrDoenteNao.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jrDoenteNao.setForeground(new java.awt.Color(56, 0, 56));
        jrDoenteNao.setText("Não");
        jrDoenteNao.setOpaque(false);
        jrDoenteNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrDoenteNaoActionPerformed(evt);
            }
        });
        add(jrDoenteNao, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 550, -1, 30));

        pnDoencas.setBackground(new java.awt.Color(255, 255, 255));
        pnDoencas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbdoenca.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jlbdoenca.setForeground(new java.awt.Color(56, 0, 56));
        jlbdoenca.setText("Quais doenças");
        pnDoencas.add(jlbdoenca, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jtxdoenca.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jtxdoenca.setForeground(new java.awt.Color(56, 0, 56));
        jtxdoenca.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(131, 106, 131), 1, true));
        jtxdoenca.setSelectionColor(new java.awt.Color(149, 113, 149));
        pnDoencas.add(jtxdoenca, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 190, 30));

        add(pnDoencas, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 550, -1, 30));
        add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, 60, -1));

        jtx_descricao.setColumns(20);
        jtx_descricao.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jtx_descricao.setForeground(new java.awt.Color(56, 0, 56));
        jtx_descricao.setLineWrap(true);
        jtx_descricao.setRows(5);
        jtx_descricao.setTabSize(0);
        jtx_descricao.setWrapStyleWord(true);
        jtx_descricao.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jtx_descricao.setHighlighter(null);
        jtx_descricao.setSelectionColor(new java.awt.Color(149, 113, 149));
        jScrollPane1.setViewportView(jtx_descricao);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 630, 490, -1));

        txt_imagem.setBackground(new java.awt.Color(255, 255, 255));
        txt_imagem.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        txt_imagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_imagem.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(204, 204, 204)));
        add(txt_imagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 810, 200, 150));
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 1000, 20, 20));

        jpnAddFoto.setBackground(new java.awt.Color(56, 0, 56));
        jpnAddFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnAddFotoMouseClicked(evt);
            }
        });
        jpnAddFoto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-mais-20 (1).png"))); // NOI18N
        jpnAddFoto.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        add(jpnAddFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 970, 30, 30));

        jpnExcluirFoto.setBackground(new java.awt.Color(56, 0, 56));
        jpnExcluirFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnExcluirFotoMouseClicked(evt);
            }
        });
        jpnExcluirFoto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-cancelar-20 (1).png"))); // NOI18N
        jpnExcluirFoto.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        add(jpnExcluirFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 970, 30, 30));

        jSlider1.setBackground(new java.awt.Color(255, 255, 255));
        jSlider1.setForeground(new java.awt.Color(56, 0, 56));
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 300, 30));

        getAccessibleContext().setAccessibleName("panelCadastro");
    }// </editor-fold>//GEN-END:initComponents
    private void backgroundComboBox(JComboBox jcb) {
        jcb.setBackground(Color.WHITE);
    }
    private void jComboEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboEspecieActionPerformed
        jpQual.setVisible("Outro".equals(jComboEspecie.getSelectedItem()));
    }//GEN-LAST:event_jComboEspecieActionPerformed

    public boolean qualbg(ButtonGroup b) {
        return b.getSelection().equals("Sim");
    }
    
    private void cadastrarAnimal() throws IOException{
        
        
        
//        
//        String filePath = "C:/Users/Gilberto/Desktop/a.jpg";
//        byte[] fileContent = FileUtils.readFileToByteArray(new File(filePath));
//        String encodedString = Base64.getEncoder().encodeToString(fileContent);
//        Animal a = new Animal("nome", 1, "especie", "raca", 
//                "cor", "porte", "sexo",
//                "descricao",null, 
//                "qualDoenca", true, true, true, encodedString);
        
        
            try {
                animal = colherInformacao();
            } catch (SQLException ex) {
                Logger.getLogger(TelaDeCadastroDeAnimais.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(TelaDeCadastroDeAnimais.class.getName()).log(Level.SEVERE, null, ex);
            }
            new Thread(new Runnable() {
            public void run() {
                JFrame frame;
                frame = new TelaLoading();
                frame.pack();
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);
                frame.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
                             
                try {
                    Thread.sleep(1000);
                    cAnimal.insert(animal);
                } catch (Exception ex) {
                    Logger.getLogger(TelaDeCadastroDeAnimais.class.getName()).log(Level.SEVERE, null, ex);
                }
                frame.setVisible(false);
                frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                frame.dispatchEvent(new WindowEvent(frame, WindowEvent.WINDOW_CLOSING));
            }
            }).start();
            
                
            
            
            
            //frame.setVisible(false);
            
                
 
        
    }
    
    private void btn_cadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cadastrarMouseClicked
        
        try {
            cadastrarAnimal();
        } catch (IOException ex) {
            Logger.getLogger(TelaDeCadastroDeAnimais.class.getName()).log(Level.SEVERE, null, ex);
        }
        limparComponentes();
        
    }//GEN-LAST:event_btn_cadastrarMouseClicked

    private void limparComponentes(){
        jComboEspecie.setSelectedIndex(1);
        jpQual.setVisible(false);
        jtx_nome.setText("");
        jSlider1.setValue(jSlider1.getMaximum()/2);
        jComboPorte.setSelectedIndex(1);
        jtx_raca.setText("");
        jtx_cor.setText("");
        jrMacho.setSelected(false);
        rjFemea.setSelected(false);
        jrVacinadoSim.setSelected(false);
        jrVacinadoNao.setSelected(false);
        jrCastradoSim.setSelected(false);
        jrCastradoNao.setSelected(false);
        jrDoenteSim.setSelected(false);
        jrDoenteNao.setSelected(false);
        jtxdoenca.setText("");
        pnDoencas.setVisible(false);
        jtx_descricao.setText("");
        txt_imagem.setIcon(null);
    }
    private void jrMachoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrMachoActionPerformed
        // TODO add your handling code here:
        rjFemea.setSelected(false);
    }//GEN-LAST:event_jrMachoActionPerformed

    private void rjFemeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rjFemeaActionPerformed

        jrMacho.setSelected(false);
    }//GEN-LAST:event_rjFemeaActionPerformed

    private void jrDoenteSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrDoenteSimActionPerformed
        // TODO add your handling code here:
        pnDoencas.setVisible(true);
        jtxdoenca.setText("");
    }//GEN-LAST:event_jrDoenteSimActionPerformed

    private void jrDoenteNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrDoenteNaoActionPerformed
        // TODO add your handling code here:
        pnDoencas.setVisible(false);
        jtxdoenca.setText("");
    }//GEN-LAST:event_jrDoenteNaoActionPerformed

    private void jpnAddFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnAddFotoMouseClicked
        adicionarImagem(txt_imagem);
    }//GEN-LAST:event_jpnAddFotoMouseClicked

    private void jpnExcluirFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnExcluirFotoMouseClicked
        ImagemIconAnimal = null;
        txt_imagem.setIcon(null);

    }//GEN-LAST:event_jpnExcluirFotoMouseClicked

    private void jComboEspecie1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboEspecie1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboEspecie1ActionPerformed

    private void btn_cadastrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cadastrar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cadastrar1MouseClicked

    private void jtx_nomeContato1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtx_nomeContato1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtx_nomeContato1ActionPerformed

    private void jrMacho1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrMacho1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrMacho1ActionPerformed

    private void rjFemea1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rjFemea1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rjFemea1ActionPerformed

    private void jrDoenteSim1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrDoenteSim1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrDoenteSim1ActionPerformed

    private void jrDoenteNao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrDoenteNao1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrDoenteNao1ActionPerformed

    private void jrAcidentadoSim1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrAcidentadoSim1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrAcidentadoSim1ActionPerformed

    private void jrAcidentadoNao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrAcidentadoNao1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrAcidentadoNao1ActionPerformed

    private void jrComunitarioSim1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrComunitarioSim1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrComunitarioSim1ActionPerformed

    private void jrComunitarioNao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrComunitarioNao1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrComunitarioNao1ActionPerformed

    private void jpnAddFoto1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnAddFoto1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jpnAddFoto1MouseClicked

    private void jpnExcluirFoto1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnExcluirFoto1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jpnExcluirFoto1MouseClicked

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        idadeAnimal.setText(""+jSlider1.getValue());
    }//GEN-LAST:event_jSlider1StateChanged

    public Animal colherInformacao() throws SQLException, IOException {

        String nome;
        String especie;
        int idade;
        String raca;
        String cor;
        String porte;
        String sexo;
        String descricao;
        Date dataDeCadastro;
        String qualDoenca;
        //ImageIcon ImagemIcon;
        String StringImagem;
        boolean doente;
        boolean castrado;
        boolean vacinado;

        String imagemAnimal;
        //Coleta dos dados dos campos de texto
        nome = jtx_nome.getText();
        especie = jComboEspecie.getSelectedItem().toString();
        raca = jtx_raca.getText();
        cor = jtx_cor.getText();
        porte = (String) jComboPorte.getSelectedItem();

        if (jrMacho.isSelected()) {
            sexo = "Macho";
        } else {
            sexo = "Fêmea";
        }
        //sexo = cbSexoPress();
        descricao = jtx_descricao.getText();
        qualDoenca = jtxdoenca.getText();
        //Coleta de dados da barra 'slider'

        
        Calendar c = Calendar.getInstance();
        int dia = c.get(Calendar.DAY_OF_MONTH);
        int ano = c.get(Calendar.YEAR);
        int mes = c.get(Calendar.MONTH);
        //Coleta de dados da barra 'slider'

        String date = ano+"-"+(mes+1)+"-"+dia;
        System.out.println();
        java.sql.Date dat = java.sql.Date.valueOf(date);
        dataDeCadastro = dat;
        imagemAnimal = Controll_Images.ImagemParaString(ImagemIconAnimal);
        //System.out.println(imagemAnimal);
        
        vacinado = jrVacinadoSim.isSelected();

        doente = jrDoenteSim.isSelected();

        castrado = jrCastradoSim.isSelected();

        //idade = jSlider1.getValue();
        idade = 0;
        Animal animal = new Animal(nome, idade, especie, raca, 
                cor, porte, sexo,
                descricao,null, 
                qualDoenca, doente, castrado, vacinado, imagemAnimal);
        return animal;
    }

    public void adicionarImagem(JLabel fotinha) {
        JFileChooser jFileChooser1 = new javax.swing.JFileChooser(ultimoPacote);
        jFileChooser1.showOpenDialog(null);
        File arquivo = jFileChooser1.getSelectedFile();
        if (arquivo != null) {
            ultimoPacote = arquivo.getPath();
            ImageIcon imagem = new ImageIcon(ultimoPacote);
            fotinha.setIcon(redimensionar_imagem(imagem));
            ImagemIconAnimal = imagem;
        } else {
            System.out.println("Deu muito ruim");
        }
    }

    public ImageIcon redimensionar_imagem(ImageIcon img) {
        img.setImage(img.getImage().getScaledInstance(200, 150, 100));
        return img;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LABELCOMERRO;
    private javax.swing.JPanel btn_cadastrar;
    private javax.swing.JPanel btn_cadastrar1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JLabel idadeAnimal;
    private javax.swing.JComboBox<String> jComboBairro1;
    private javax.swing.JComboBox<String> jComboEspecie;
    private javax.swing.JComboBox<String> jComboEspecie1;
    private javax.swing.JComboBox<String> jComboPorte;
    private javax.swing.JComboBox<String> jComboPorte1;
    private javax.swing.JComboBox<String> jComboTemperamento1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JLabel jblPrenha1;
    private javax.swing.JLabel jlbdoenca;
    private javax.swing.JLabel jlbdoenca1;
    private javax.swing.JLabel jlbdoenca3;
    private javax.swing.JPanel jpQual;
    private javax.swing.JPanel jpQual1;
    private javax.swing.JPanel jpnAddFoto;
    private javax.swing.JPanel jpnAddFoto1;
    private javax.swing.JPanel jpnExcluirFoto;
    private javax.swing.JPanel jpnExcluirFoto1;
    private javax.swing.JRadioButton jrAcidentadoNao1;
    private javax.swing.JRadioButton jrAcidentadoSim1;
    private javax.swing.JRadioButton jrCastradoNao;
    private javax.swing.JRadioButton jrCastradoNao1;
    private javax.swing.JRadioButton jrCastradoSim;
    private javax.swing.JRadioButton jrCastradoSim1;
    private javax.swing.JRadioButton jrComunitarioNao1;
    private javax.swing.JRadioButton jrComunitarioSim1;
    private javax.swing.JRadioButton jrDoenteNao;
    private javax.swing.JRadioButton jrDoenteNao1;
    private javax.swing.JRadioButton jrDoenteSim;
    private javax.swing.JRadioButton jrDoenteSim1;
    private javax.swing.JRadioButton jrMacho;
    private javax.swing.JRadioButton jrMacho1;
    private javax.swing.JRadioButton jrPrenhaNao1;
    private javax.swing.JRadioButton jrPrenhaSim1;
    private javax.swing.JRadioButton jrVacinadoNao;
    private javax.swing.JRadioButton jrVacinadoNao1;
    private javax.swing.JRadioButton jrVacinadoSim;
    private javax.swing.JRadioButton jrVacinadoSim1;
    private javax.swing.JTextField jtx_cor;
    private javax.swing.JTextField jtx_cor1;
    private javax.swing.JTextArea jtx_descricao;
    private javax.swing.JTextArea jtx_descricao1;
    private javax.swing.JFormattedTextField jtx_idade1;
    private javax.swing.JTextField jtx_nome;
    private javax.swing.JTextField jtx_nome1;
    private javax.swing.JTextField jtx_nomeContato1;
    private javax.swing.JTextField jtx_raca;
    private javax.swing.JTextField jtx_raca1;
    private javax.swing.JFormattedTextField jtx_telefoneContato1;
    private javax.swing.JTextField jtxacidente1;
    private javax.swing.JTextField jtxdoenca;
    private javax.swing.JTextField jtxdoenca1;
    private javax.swing.JTextField jtxoutraraca;
    private javax.swing.JTextField jtxoutraraca1;
    private javax.swing.JPanel panelTamanho;
    private javax.swing.JPanel panelTamanho1;
    private javax.swing.JPanel pnAcidentado1;
    private javax.swing.JPanel pnDoencas;
    private javax.swing.JPanel pnDoencas1;
    private javax.swing.JPanel pnPrenha1;
    private javax.swing.JLabel qual;
    private javax.swing.JLabel qual2;
    private javax.swing.JLabel qual3;
    private javax.swing.JRadioButton rjFemea;
    private javax.swing.JRadioButton rjFemea1;
    private javax.swing.JLabel somente1;
    private javax.swing.JLabel txt_imagem;
    private javax.swing.JLabel txt_imagem1;
    // End of variables declaration//GEN-END:variables
}
